apiVersion: v1
kind: Service
metadata:
  name: redi-service
  labels:
    name: redis-service
    type: example-voting-app
spec:
  ports:
  -  port: 6379
     tagretport: 6379
  selector:
    name: redis-pod
    type: example-voting-app
    
 