apiVersion: v1
kind: Pod
metadata: 
  name: exampl-result-pod
  labels:
    name: example-result-pod
    type: example-voting-app
spec:
  containers:
  -  name: example-result-pod
     image: dockersamples/examplevotingapp_result
     ports:
     - containerPort: 80
     