apiVersion: v1
kind: Pod
metadata: 
  name: example-voting-app
  labels:
    name: example-voting-app
    type: voting app
spec:
  containers:
  -  name: emaple-vote-app
     image: dockersamples/examplevotingapp_vote
     ports:
     - containerPort: 80