apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    type: example-voting-app
spec:
  containers:
  -  name: worker-pod
     image: dockersamples/examplevotingapp_worker
